export const PRODUCTS_SEED = [
  {
    slug: "classic-swiss-muesli",
    name: "Classic Swiss Muesli",
    shortDescription:
      "Wholesome rolled oats blended with dried fruits, nuts & seeds for the perfect morning start.",
    description:
      "Our Classic Swiss Muesli is crafted from premium rolled oats sourced from select farms, combined with a vibrant medley of sun-dried fruits, roasted nuts, and nutrient-rich seeds. Each spoonful delivers a harmonious balance of complex carbohydrates, natural fiber, and essential minerals that fuel your morning the natural way. Ready in minutes — simply soak overnight or enjoy with warm milk.",
    price: "850",
    comparePrice: "999",
    imageUrl: "/images/product-muesli.jpg",
    images: ["/images/product-muesli.jpg"],
    category: "Breakfast Cereals",
    weight: "400g",
    inStock: true,
    featured: true,
    badge: "Best Seller",
    ingredients:
      "Rolled Oats (55%), Raisins, Roasted Almonds, Sunflower Seeds, Pumpkin Seeds, Dried Cranberries, Dried Apricots, Coconut Flakes, Natural Honey Granules",
    benefits: [
      "High in dietary fiber for healthy digestion",
      "Slow-release energy to keep you fuller longer",
      "Rich in Omega-3 fatty acids from seeds",
      "No artificial colors, flavors or preservatives",
      "Halal certified & Vegetarian friendly",
    ],
    nutritionalFacts: [
      { label: "Calories", value: "378 kcal", per100g: "per 100g" },
      { label: "Total Fat", value: "9.2g", per100g: "per 100g" },
      { label: "Saturated Fat", value: "1.8g", per100g: "per 100g" },
      { label: "Total Carbohydrate", value: "62g", per100g: "per 100g" },
      { label: "Dietary Fiber", value: "8.4g", per100g: "per 100g" },
      { label: "Total Sugars", value: "18g", per100g: "per 100g" },
      { label: "Protein", value: "10.5g", per100g: "per 100g" },
      { label: "Sodium", value: "12mg", per100g: "per 100g" },
      { label: "Calcium", value: "52mg", per100g: "per 100g" },
      { label: "Iron", value: "3.6mg", per100g: "per 100g" },
    ],
    certifications: ["PSQCA Certified", "Halal Certified", "ISO 22000"],
  },
  {
    slug: "instant-oatmeal-classic",
    name: "Instant Oatmeal Classic",
    shortDescription:
      "Quick-cook premium oats packed with beta-glucan for heart health — ready in 3 minutes.",
    description:
      "Bereket Naturals Instant Oatmeal is made from 100% whole-grain oats, steam-processed to retain all the natural goodness while making them quick and easy to prepare. Rich in beta-glucan fiber, clinically shown to support healthy cholesterol levels and sustained energy. Available in natural unflavored form — add your own fruits, honey, or nut butter for a personalized bowl.",
    price: "650",
    comparePrice: "799",
    imageUrl: "/images/product-oatmeal.jpg",
    images: ["/images/product-oatmeal.jpg"],
    category: "Breakfast Cereals",
    weight: "500g",
    inStock: true,
    featured: true,
    badge: "New",
    ingredients:
      "100% Whole Grain Rolled Oats (Avena sativa). May contain traces of nuts and seeds.",
    benefits: [
      "Beta-glucan fiber supports heart health",
      "Ready in just 3 minutes",
      "High in whole grain goodness",
      "Gluten-processed in dedicated facility",
      "Suitable for diabetics (low GI)",
    ],
    nutritionalFacts: [
      { label: "Calories", value: "389 kcal", per100g: "per 100g" },
      { label: "Total Fat", value: "6.9g", per100g: "per 100g" },
      { label: "Saturated Fat", value: "1.2g", per100g: "per 100g" },
      { label: "Total Carbohydrate", value: "66g", per100g: "per 100g" },
      { label: "Dietary Fiber", value: "10.6g", per100g: "per 100g" },
      { label: "Beta-Glucan", value: "4g", per100g: "per 100g" },
      { label: "Total Sugars", value: "1.1g", per100g: "per 100g" },
      { label: "Protein", value: "16.9g", per100g: "per 100g" },
      { label: "Sodium", value: "2mg", per100g: "per 100g" },
      { label: "Iron", value: "4.7mg", per100g: "per 100g" },
    ],
    certifications: ["PSQCA Certified", "Halal Certified"],
  },
  {
    slug: "honey-nut-granola",
    name: "Honey & Nut Granola",
    shortDescription:
      "Crunchy golden clusters of oats, nuts & honey — your perfect guilt-free snack.",
    description:
      "Our Honey & Nut Granola is slow-baked at low temperature to create perfectly crunchy clusters without destroying the natural nutrients. A golden blend of oats, wildflower honey, roasted nuts, and coconut creates an irresistible texture and flavor. Enjoy as a cereal, yogurt topper, or straight from the bag as a satisfying snack.",
    price: "950",
    comparePrice: "1100",
    imageUrl: "/images/product-granola.jpg",
    images: ["/images/product-granola.jpg"],
    category: "Granola & Snacks",
    weight: "350g",
    inStock: true,
    featured: true,
    badge: "Fan Favorite",
    ingredients:
      "Rolled Oats (45%), Wildflower Honey (12%), Roasted Cashews, Roasted Almonds, Coconut Flakes, Sunflower Oil, Brown Sugar, Vanilla Extract, Sea Salt",
    benefits: [
      "Slow-baked for maximum crunch & nutrition",
      "Natural wildflower honey — no corn syrup",
      "Source of plant-based protein",
      "Excellent source of magnesium & zinc",
      "No artificial additives",
    ],
    nutritionalFacts: [
      { label: "Calories", value: "450 kcal", per100g: "per 100g" },
      { label: "Total Fat", value: "18g", per100g: "per 100g" },
      { label: "Saturated Fat", value: "4.5g", per100g: "per 100g" },
      { label: "Total Carbohydrate", value: "62g", per100g: "per 100g" },
      { label: "Dietary Fiber", value: "5.2g", per100g: "per 100g" },
      { label: "Total Sugars", value: "24g", per100g: "per 100g" },
      { label: "Protein", value: "9.8g", per100g: "per 100g" },
      { label: "Sodium", value: "85mg", per100g: "per 100g" },
      { label: "Potassium", value: "320mg", per100g: "per 100g" },
    ],
    certifications: ["PSQCA Certified", "Halal Certified"],
  },
  {
    slug: "organic-chia-seeds",
    name: "Organic Chia Seeds",
    shortDescription:
      "Superfood chia seeds packed with Omega-3, fiber & complete protein.",
    description:
      "Bereket Naturals Organic Chia Seeds are sourced from certified organic farms and carefully cleaned to ensure maximum purity. These tiny powerhouses are one of the richest plant-based sources of Omega-3 fatty acids, fiber, and complete protein containing all essential amino acids. Use in puddings, smoothies, baking, or as an egg substitute.",
    price: "750",
    comparePrice: null,
    imageUrl: "/images/product-chia.jpg",
    images: ["/images/product-chia.jpg"],
    category: "Superfoods",
    weight: "250g",
    inStock: true,
    featured: false,
    badge: "Organic",
    ingredients:
      "100% Organic Chia Seeds (Salvia hispanica L.). Certified Organic. Non-GMO.",
    benefits: [
      "Highest plant-based Omega-3 (ALA) content",
      "Forms a gel that promotes satiety",
      "Complete protein with all amino acids",
      "Supports bone health with calcium & phosphorus",
      "Versatile superfood for any meal",
    ],
    nutritionalFacts: [
      { label: "Calories", value: "486 kcal", per100g: "per 100g" },
      { label: "Total Fat", value: "30.7g", per100g: "per 100g" },
      { label: "Omega-3 (ALA)", value: "17.5g", per100g: "per 100g" },
      { label: "Total Carbohydrate", value: "42.1g", per100g: "per 100g" },
      { label: "Dietary Fiber", value: "34.4g", per100g: "per 100g" },
      { label: "Total Sugars", value: "0g", per100g: "per 100g" },
      { label: "Protein", value: "16.5g", per100g: "per 100g" },
      { label: "Calcium", value: "631mg", per100g: "per 100g" },
      { label: "Iron", value: "7.7mg", per100g: "per 100g" },
      { label: "Magnesium", value: "335mg", per100g: "per 100g" },
    ],
    certifications: [
      "USDA Organic Equivalent",
      "Halal Certified",
      "Non-GMO Verified",
    ],
  },
  {
    slug: "wild-strawberry-jam",
    name: "Wild Strawberry Jam",
    shortDescription:
      "Artisan jam crafted from hand-picked strawberries with no artificial preservatives.",
    description:
      "Our Wild Strawberry Jam is crafted in small batches from hand-selected premium strawberries at peak ripeness. Sweetened only with cane sugar and a touch of lemon, it delivers an intensely fruity flavor you'd expect from a homemade jam. Free from artificial colors, preservatives, or pectin additives.",
    price: "520",
    comparePrice: "650",
    imageUrl: "/images/product-jam.jpg",
    images: ["/images/product-jam.jpg"],
    category: "Jams & Condiments",
    weight: "340g",
    inStock: true,
    featured: false,
    badge: "Artisan",
    ingredients:
      "Strawberries (65%), Cane Sugar, Lemon Juice. No artificial preservatives, colors or flavors.",
    benefits: [
      "Made from 65% real strawberries",
      "No artificial preservatives",
      "Rich in natural Vitamin C",
      "Small-batch artisan production",
      "Pairs perfectly with our muesli & oatmeal",
    ],
    nutritionalFacts: [
      { label: "Calories", value: "250 kcal", per100g: "per 100g" },
      { label: "Total Fat", value: "0.1g", per100g: "per 100g" },
      { label: "Total Carbohydrate", value: "62g", per100g: "per 100g" },
      { label: "Dietary Fiber", value: "1.5g", per100g: "per 100g" },
      { label: "Total Sugars", value: "58g", per100g: "per 100g" },
      { label: "Protein", value: "0.5g", per100g: "per 100g" },
      { label: "Vitamin C", value: "12mg", per100g: "per 100g" },
    ],
    certifications: ["PSQCA Certified", "Halal Certified"],
  },
  {
    slug: "raw-wildflower-honey",
    name: "Raw Wildflower Honey",
    shortDescription:
      "Unfiltered, unpasteurized pure honey harvested from wildflower meadows.",
    description:
      "Our Raw Wildflower Honey is harvested from hives placed in pristine, pollution-free wildflower meadows. Unlike commercial honey, our product is never heated above the hive temperature, preserving all natural enzymes, antioxidants, and pollen. The complex floral flavor profile changes subtly with each season, reflecting the natural biodiversity of the meadow.",
    price: "1200",
    comparePrice: "1450",
    imageUrl: "/images/product-honey.jpg",
    images: ["/images/product-honey.jpg"],
    category: "Natural Sweeteners",
    weight: "500g",
    inStock: true,
    featured: true,
    badge: "Raw & Pure",
    ingredients:
      "100% Pure Raw Wildflower Honey. Unfiltered. Unpasteurized. No additives.",
    benefits: [
      "Retains all natural enzymes & antioxidants",
      "Natural antimicrobial properties",
      "Rich in pollen for allergy relief",
      "Supports immune system function",
      "Perfect natural alternative to refined sugar",
    ],
    nutritionalFacts: [
      { label: "Calories", value: "304 kcal", per100g: "per 100g" },
      { label: "Total Fat", value: "0g", per100g: "per 100g" },
      { label: "Total Carbohydrate", value: "82.4g", per100g: "per 100g" },
      { label: "Fructose", value: "38.5g", per100g: "per 100g" },
      { label: "Glucose", value: "31g", per100g: "per 100g" },
      { label: "Total Sugars", value: "82.1g", per100g: "per 100g" },
      { label: "Protein", value: "0.3g", per100g: "per 100g" },
      { label: "Potassium", value: "52mg", per100g: "per 100g" },
      { label: "Antioxidants (ORAC)", value: "796 µmolTE", per100g: "per 100g" },
    ],
    certifications: ["PSQCA Certified", "Halal Certified", "Pure Food Grade"],
  },
  {
    slug: "organic-tri-color-quinoa",
    name: "Organic Tri-Color Quinoa",
    shortDescription:
      "A complete plant protein — mix of white, red & black quinoa from certified organic farms.",
    description:
      "Bereket Naturals Tri-Color Quinoa combines white, red, and black quinoa varieties for a nutritionally superior and visually beautiful grain. As one of the very few complete plant proteins, quinoa contains all nine essential amino acids making it a must-have for vegetarians and athletes. It is naturally gluten-free, easy to digest, and cooks in just 15 minutes.",
    price: "1100",
    comparePrice: null,
    imageUrl: "/images/product-quinoa.jpg",
    images: ["/images/product-quinoa.jpg"],
    category: "Superfoods",
    weight: "400g",
    inStock: true,
    featured: false,
    badge: "Complete Protein",
    ingredients:
      "Organic White Quinoa, Organic Red Quinoa, Organic Black Quinoa. Certified Organic. Gluten-Free facility.",
    benefits: [
      "Complete protein with all 9 essential amino acids",
      "Naturally gluten-free grain",
      "High in magnesium, zinc & iron",
      "Low glycemic index — suitable for diabetics",
      "Cooks in only 15 minutes",
    ],
    nutritionalFacts: [
      { label: "Calories", value: "368 kcal", per100g: "per 100g" },
      { label: "Total Fat", value: "6.1g", per100g: "per 100g" },
      { label: "Omega-6", value: "2.9g", per100g: "per 100g" },
      { label: "Total Carbohydrate", value: "64.2g", per100g: "per 100g" },
      { label: "Dietary Fiber", value: "7g", per100g: "per 100g" },
      { label: "Total Sugars", value: "4.4g", per100g: "per 100g" },
      { label: "Protein", value: "14.1g", per100g: "per 100g" },
      { label: "Iron", value: "4.6mg", per100g: "per 100g" },
      { label: "Magnesium", value: "197mg", per100g: "per 100g" },
      { label: "Zinc", value: "3.1mg", per100g: "per 100g" },
    ],
    certifications: [
      "USDA Organic Equivalent",
      "Halal Certified",
      "Gluten-Free Certified",
    ],
  },
  {
    slug: "berry-blast-muesli",
    name: "Berry Blast Muesli",
    shortDescription:
      "Vibrant muesli loaded with freeze-dried berries, oats & coconut for a fruity breakfast.",
    description:
      "Our Berry Blast Muesli takes the beloved Swiss original to a new level with the addition of premium freeze-dried strawberries, blueberries, and raspberries. Freeze-drying locks in 98% of the original vitamins and gives each berry an intense, concentrated flavor that bloom beautifully when mixed with milk or yogurt. A colorful, nutrient-dense way to start your day.",
    price: "950",
    comparePrice: "1150",
    imageUrl: "/images/product-muesli.jpg",
    images: ["/images/product-muesli.jpg"],
    category: "Breakfast Cereals",
    weight: "400g",
    inStock: true,
    featured: false,
    badge: "Limited Edition",
    ingredients:
      "Rolled Oats (50%), Freeze-Dried Strawberries (8%), Freeze-Dried Blueberries (6%), Freeze-Dried Raspberries (5%), Coconut Flakes, Pumpkin Seeds, Sunflower Seeds, Agave Syrup",
    benefits: [
      "Freeze-dried berries retain 98% of vitamins",
      "Powerful antioxidant boost from berry trio",
      "No added refined sugar — naturally sweet",
      "High in anthocyanins for brain health",
      "Beautiful color — great for kids",
    ],
    nutritionalFacts: [
      { label: "Calories", value: "362 kcal", per100g: "per 100g" },
      { label: "Total Fat", value: "8.1g", per100g: "per 100g" },
      { label: "Total Carbohydrate", value: "60g", per100g: "per 100g" },
      { label: "Dietary Fiber", value: "9.2g", per100g: "per 100g" },
      { label: "Total Sugars", value: "20g", per100g: "per 100g" },
      { label: "Protein", value: "10.1g", per100g: "per 100g" },
      { label: "Vitamin C", value: "18mg", per100g: "per 100g" },
      { label: "Antioxidants", value: "High", per100g: "per 100g" },
    ],
    certifications: ["PSQCA Certified", "Halal Certified"],
  },
];
