export const PRODUCTS_SEED = [
  // JARFULL PRODUCTS
  {
    slug: "green-chilli-paste",
    name: "Green Chilli Paste",
    shortDescription: "Fresh and tangy green chilli paste - perfect condiment for every meal.",
    description: "Jarfull Green Chilli Paste is made from fresh green chilies with authentic spices. Perfect for adding flavor to dishes, dips, and sandwiches.",
    price: "320",
    comparePrice: "400",
    imageUrl: "/assets/images/products/jarfull/green-chilli-paste.jpg",
    images: ["/assets/images/products/jarfull/green-chilli-paste.jpg"],
    category: "Condiments & Pastes",
    brand: "Jarfull",
    weight: "300g",
    inStock: true,
    featured: false,
    badge: "Best Seller",
  },
  {
    slug: "mango-chutney",
    name: "Mango Chutney",
    shortDescription: "Sweet and tangy mango chutney with aromatic spices.",
    description: "Jarfull Mango Chutney is crafted from premium mangoes with a perfect blend of spices. Great with bread, rice, and curry dishes.",
    price: "350",
    comparePrice: "430",
    imageUrl: "/assets/images/products/jarfull/mango-chutney.jpg",
    images: ["/assets/images/products/jarfull/mango-chutney.jpg"],
    category: "Condiments & Pastes",
    brand: "Jarfull",
    weight: "300g",
    inStock: true,
    featured: true,
    badge: "Best Seller",
  },
  {
    slug: "mixed-pickle",
    name: "Mixed Pickle",
    shortDescription: "Traditional mixed vegetable pickle with authentic spices.",
    description: "Jarfull Mixed Pickle brings together a harmonious blend of fresh vegetables preserved with traditional spices and vinegar.",
    price: "280",
    comparePrice: "350",
    imageUrl: "/assets/images/products/jarfull/mixed-pickle.jpg",
    images: ["/assets/images/products/jarfull/mixed-pickle.jpg"],
    category: "Pickles & Preserved Foods",
    brand: "Jarfull",
    weight: "350g",
    inStock: true,
    featured: false,
  },
  {
    slug: "mixed-pickle-2",
    name: "Mixed Pickle Premium",
    shortDescription: "Premium selection of vegetables in a special blend of spices.",
    description: "Jarfull Premium Mixed Pickle offers a selection of hand-picked vegetables in our signature spice blend.",
    price: "320",
    comparePrice: "400",
    imageUrl: "/assets/images/products/jarfull/mixed-pickle-2.jpg",
    images: ["/assets/images/products/jarfull/mixed-pickle-2.jpg"],
    category: "Pickles & Preserved Foods",
    brand: "Jarfull",
    weight: "350g",
    inStock: true,
    featured: false,
  },
  {
    slug: "plum-chutney",
    name: "Plum Chutney",
    shortDescription: "Unique sweet plum chutney with a perfect balance of flavors.",
    description: "Jarfull Plum Chutney is an innovative condiment made from premium plums with aromatic spices.",
    price: "360",
    comparePrice: "450",
    imageUrl: "/assets/images/products/jarfull/plum-chutney.jpg",
    images: ["/assets/images/products/jarfull/plum-chutney.jpg"],
    category: "Condiments & Pastes",
    brand: "Jarfull",
    weight: "300g",
    inStock: true,
    featured: false,
  },
  {
    slug: "tomato-ketchup-green",
    name: "Tomato Ketchup Green",
    shortDescription: "Traditional green tomato ketchup with authentic taste.",
    description: "Jarfull Green Tomato Ketchup is made from selected green tomatoes with a blend of spices and vinegar.",
    price: "250",
    comparePrice: "320",
    imageUrl: "/assets/images/products/jarfull/tomato-ketchup-green.jpg",
    images: ["/assets/images/products/jarfull/tomato-ketchup-green.jpg"],
    category: "Condiments & Pastes",
    brand: "Jarfull",
    weight: "350g",
    inStock: true,
    featured: false,
  },
  {
    slug: "tomato-ketchup-red",
    name: "Tomato Ketchup Red",
    shortDescription: "Rich red tomato ketchup for family meals.",
    description: "Jarfull Red Tomato Ketchup is prepared from the finest red tomatoes with no artificial preservatives.",
    price: "270",
    comparePrice: "340",
    imageUrl: "/assets/images/products/jarfull/tomato-ketchup-red.jpg",
    images: ["/assets/images/products/jarfull/tomato-ketchup-red.jpg"],
    category: "Condiments & Pastes",
    brand: "Jarfull",
    weight: "350g",
    inStock: true,
    featured: true,
    badge: "Popular",
  },

  // JHAT HAZAM PRODUCTS
  {
    slug: "aamchoor-powder",
    name: "Aamchoor Powder",
    shortDescription: "Dry mango powder - authentic spice for Indian cooking.",
    description: "Jhat Hazam Aamchoor Powder is made from dried mango, providing authentic tangy flavor to your dishes.",
    price: "420",
    comparePrice: "520",
    imageUrl: "/assets/images/products/jhat-hazam/aamchoor.jpg",
    images: ["/assets/images/products/jhat-hazam/aamchoor.jpg"],
    category: "Spices & Seasonings",
    brand: "Jhat Hazam",
    weight: "200g",
    inStock: true,
    featured: false,
  },
  {
    slug: "amrud-paste",
    name: "Amrud Paste",
    shortDescription: "Guava paste - sweet and aromatic condiment.",
    description: "Jhat Hazam Amrud (Guava) Paste is a traditional preparation with natural sweetness.",
    price: "350",
    comparePrice: "430",
    imageUrl: "/assets/images/products/jhat-hazam/amrud.jpg",
    images: ["/assets/images/products/jhat-hazam/amrud.jpg"],
    category: "Condiments & Pastes",
    brand: "Jhat Hazam",
    weight: "300g",
    inStock: true,
    featured: false,
  },
  {
    slug: "anaar-paste",
    name: "Anaar Paste",
    shortDescription: "Pomegranate paste - rich and flavorful.",
    description: "Jhat Hazam Anaar (Pomegranate) Paste brings the authentic taste of pomegranate to your kitchen.",
    price: "380",
    comparePrice: "480",
    imageUrl: "/assets/images/products/jhat-hazam/anaar.jpg",
    images: ["/assets/images/products/jhat-hazam/anaar.jpg"],
    category: "Condiments & Pastes",
    brand: "Jhat Hazam",
    weight: "300g",
    inStock: true,
    featured: true,
  },
  {
    slug: "cola-drink-syrup",
    name: "Cola Drink Syrup",
    shortDescription: "Traditional cola syrup for homemade beverages.",
    description: "Jhat Hazam Cola Syrup is a traditional drink concentrate for refreshing beverages.",
    price: "300",
    comparePrice: "380",
    imageUrl: "/assets/images/products/jhat-hazam/cola.jpg",
    images: ["/assets/images/products/jhat-hazam/cola.jpg"],
    category: "Beverages",
    brand: "Jhat Hazam",
    weight: "500ml",
    inStock: true,
    featured: false,
  },
  {
    slug: "imlee-paste",
    name: "Imlee Paste",
    shortDescription: "Tamarind paste - sour and delicious.",
    description: "Jhat Hazam Imlee (Tamarind) Paste is prepared from premium tamarind fruit.",
    price: "320",
    comparePrice: "400",
    imageUrl: "/assets/images/products/jhat-hazam/imlee.jpg",
    images: ["/assets/images/products/jhat-hazam/imlee.jpg"],
    category: "Condiments & Pastes",
    brand: "Jhat Hazam",
    weight: "300g",
    inStock: true,
    featured: false,
  },

  // KUVVET PRODUCTS
  {
    slug: "barley-porridge-box",
    name: "Barley Porridge Box",
    shortDescription: "Nutritious barley porridge in convenient box packaging.",
    description: "Kuvvet Barley Porridge provides complete nutrition in a convenient box. Ready to cook in minutes.",
    price: "550",
    comparePrice: "680",
    imageUrl: "/assets/images/products/kuvvet/barley-porridge-box.jpg",
    images: ["/assets/images/products/kuvvet/barley-porridge-box.jpg"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "400g",
    inStock: true,
    featured: true,
    badge: "Best Seller",
  },
  {
    slug: "barley-porridge-pouch",
    name: "Barley Porridge Pouch",
    shortDescription: "Convenient pouch porridge - great for on-the-go.",
    description: "Kuvvet Barley Porridge in a pouch offers ultimate convenience for busy mornings.",
    price: "520",
    comparePrice: "650",
    imageUrl: "/assets/images/products/kuvvet/barley-porridge-pouch.jpg",
    images: ["/assets/images/products/kuvvet/barley-porridge-pouch.jpg"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "350g",
    inStock: true,
    featured: false,
  },
  {
    slug: "berry-rocks-cereal",
    name: "Berry Rocks Cereal",
    shortDescription: "Crunchy cereal with berry flavor and fruit pieces.",
    description: "Kuvvet Berry Rocks are crunchy cereal pieces loaded with real berry flavor.",
    price: "480",
    comparePrice: "600",
    imageUrl: "/assets/images/products/kuvvet/berry-rocks.jpg",
    images: ["/assets/images/products/kuvvet/berry-rocks.jpg"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "300g",
    inStock: true,
    featured: false,
  },
  {
    slug: "choco-rocks-cereal",
    name: "Choco Rocks Cereal",
    shortDescription: "Delicious chocolate flavored crunchy cereal.",
    description: "Kuvvet Choco Rocks deliver the perfect combination of crunch and chocolate goodness.",
    price: "500",
    comparePrice: "620",
    imageUrl: "/assets/images/products/kuvvet/choco-rocks.jpg",
    images: ["/assets/images/products/kuvvet/choco-rocks.jpg"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "300g",
    inStock: true,
    featured: true,
  },
  {
    slug: "choco-shells-500g",
    name: "Choco Shells 500g",
    shortDescription: "Chocolate shell shaped cereal - family size.",
    description: "Kuvvet Choco Shells in 500g size are perfect for families who love chocolate cereal.",
    price: "560",
    comparePrice: "700",
    imageUrl: "/assets/images/products/kuvvet/choco-shells-500g.jpg",
    images: ["/assets/images/products/kuvvet/choco-shells-500g.jpg"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "500g",
    inStock: true,
    featured: false,
  },
  {
    slug: "choco-vanilla-assorted",
    name: "Choco Vanilla Assorted",
    shortDescription: "Mix of chocolate and vanilla flavored cereal.",
    description: "Kuvvet Choco Vanilla Assorted brings together the best of both flavors in one box.",
    price: "520",
    comparePrice: "650",
    imageUrl: "/assets/images/products/kuvvet/choco-vanilla-assorted.jpg",
    images: ["/assets/images/products/kuvvet/choco-vanilla-assorted.jpg"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "400g",
    inStock: true,
    featured: false,
  },
  {
    slug: "frosted-flakes-250g",
    name: "Frosted Flakes 250g",
    shortDescription: "Classic frosted corn flakes - crispy and delicious.",
    description: "Kuvvet Frosted Flakes are light, crispy corn flakes with a touch of sweetness.",
    price: "380",
    comparePrice: "480",
    imageUrl: "/assets/images/products/kuvvet/frosted-flakes-250g.webp",
    images: ["/assets/images/products/kuvvet/frosted-flakes-250g.webp"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "250g",
    inStock: true,
    featured: false,
  },
  {
    slug: "prime-flakes-500g",
    name: "Prime Flakes 500g",
    shortDescription: "Premium flakes cereal in larger size.",
    description: "Kuvvet Prime Flakes are high-quality cereal flakes offering great value.",
    price: "520",
    comparePrice: "650",
    imageUrl: "/assets/images/products/kuvvet/prime-flakes-500g.webp",
    images: ["/assets/images/products/kuvvet/prime-flakes-500g.webp"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "500g",
    inStock: true,
    featured: false,
  },
  {
    slug: "wheat-porridge-box",
    name: "Wheat Porridge Box",
    shortDescription: "Wholesome wheat porridge with complete nutrition.",
    description: "Kuvvet Wheat Porridge provides essential nutrients for a healthy breakfast.",
    price: "480",
    comparePrice: "600",
    imageUrl: "/assets/images/products/kuvvet/wheat-porridge-box.jpg",
    images: ["/assets/images/products/kuvvet/wheat-porridge-box.jpg"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "400g",
    inStock: true,
    featured: true,
  },
  {
    slug: "wheat-porridge",
    name: "Wheat Porridge",
    shortDescription: "Nutritious wheat porridge for healthy mornings.",
    description: "Kuvvet Wheat Porridge is made from premium wheat grains.",
    price: "450",
    comparePrice: "560",
    imageUrl: "/assets/images/products/kuvvet/wheat-porridge.jpg",
    images: ["/assets/images/products/kuvvet/wheat-porridge.jpg"],
    category: "Breakfast Cereals",
    brand: "Kuvvet",
    weight: "350g",
    inStock: true,
    featured: false,
  },

  // LIFFEST PRODUCTS
  {
    slug: "choco-stars-cereal",
    name: "Choco Stars",
    shortDescription: "Star-shaped chocolate flavored cereal.",
    description: "Liffest Choco Stars are fun star-shaped cereal pieces with rich chocolate flavor.",
    price: "420",
    comparePrice: "520",
    imageUrl: "/assets/images/products/liffest/choco stars.webp",
    images: ["/assets/images/products/liffest/choco stars.webp"],
    category: "Breakfast Cereals",
    brand: "Liffest",
    weight: "300g",
    inStock: true,
    featured: false,
  },
  {
    slug: "choco-balls-450g",
    name: "Choco Balls 450g",
    shortDescription: "Delicious chocolate balls cereal - family pack.",
    description: "Liffest Choco Balls in 450g size provide a great value option for chocolate cereal lovers.",
    price: "480",
    comparePrice: "600",
    imageUrl: "/assets/images/products/liffest/choco-balls-450g.webp",
    images: ["/assets/images/products/liffest/choco-balls-450g.webp"],
    category: "Breakfast Cereals",
    brand: "Liffest",
    weight: "450g",
    inStock: true,
    featured: true,
  },
  {
    slug: "choco-loops-100g",
    name: "Choco Loops 100g",
    shortDescription: "Chocolate loop cereal in travel size.",
    description: "Liffest Choco Loops in 100g size are perfect for snacking on the go.",
    price: "180",
    comparePrice: "220",
    imageUrl: "/assets/images/products/liffest/choco-loops-100g.webp",
    images: ["/assets/images/products/liffest/choco-loops-100g.webp"],
    category: "Breakfast Cereals",
    brand: "Liffest",
    weight: "100g",
    inStock: true,
    featured: false,
  },
  {
    slug: "choco-loops-250g",
    name: "Choco Loops 250g",
    shortDescription: "Chocolate loop cereal - medium pack.",
    description: "Liffest Choco Loops are delicious O-shaped cereal with chocolate coating.",
    price: "340",
    comparePrice: "420",
    imageUrl: "/assets/images/products/liffest/choco-loops-250g.webp",
    images: ["/assets/images/products/liffest/choco-loops-250g.webp"],
    category: "Breakfast Cereals",
    brand: "Liffest",
    weight: "250g",
    inStock: true,
    featured: true,
  },
  {
    slug: "choco-shells-100g",
    name: "Choco Shells 100g",
    shortDescription: "Chocolate shell cereal in small size.",
    description: "Liffest Choco Shells in 100g size are perfect for trying or traveling.",
    price: "200",
    comparePrice: "250",
    imageUrl: "/assets/images/products/liffest/choco-shells-100g.webp",
    images: ["/assets/images/products/liffest/choco-shells-100g.webp"],
    category: "Breakfast Cereals",
    brand: "Liffest",
    weight: "100g",
    inStock: true,
    featured: false,
  },
  {
    slug: "choco-shells-150g",
    name: "Choco Shells 150g",
    shortDescription: "Chocolate shell cereal - handy size.",
    description: "Liffest Choco Shells are crunchy shell-shaped cereal pieces with chocolate flavor.",
    price: "260",
    comparePrice: "320",
    imageUrl: "/assets/images/products/liffest/choco-shells-150g.webp",
    images: ["/assets/images/products/liffest/choco-shells-150g.webp"],
    category: "Breakfast Cereals",
    brand: "Liffest",
    weight: "150g",
    inStock: true,
    featured: false,
  },

  // MAJOR GRAINS PRODUCTS
  {
    slug: "major-choco-balls",
    name: "Major Grains Choco Balls",
    shortDescription: "Premium chocolate ball cereal from Major Grains.",
    description: "Major Grains Choco Balls offer superior quality and taste.",
    price: "520",
    comparePrice: "650",
    imageUrl: "/assets/images/products/major-grains/choco-balls-new.webp",
    images: ["/assets/images/products/major-grains/choco-balls-new.webp"],
    category: "Breakfast Cereals",
    brand: "Major Grains",
    weight: "350g",
    inStock: true,
    featured: false,
  },
  {
    slug: "major-choco-loops",
    name: "Major Grains Choco Loops",
    shortDescription: "Premium chocolate loops cereal.",
    description: "Major Grains Choco Loops are crafted with premium ingredients.",
    price: "480",
    comparePrice: "600",
    imageUrl: "/assets/images/products/major-grains/choco-loops-new.webp",
    images: ["/assets/images/products/major-grains/choco-loops-new.webp"],
    category: "Breakfast Cereals",
    brand: "Major Grains",
    weight: "350g",
    inStock: true,
    featured: false,
  },
  {
    slug: "major-choco-shells",
    name: "Major Grains Choco Shells",
    shortDescription: "Premium chocolate shell cereal.",
    description: "Major Grains Choco Shells deliver excellent crunch and flavor.",
    price: "500",
    comparePrice: "620",
    imageUrl: "/assets/images/products/major-grains/choco-shells-new.webp",
    images: ["/assets/images/products/major-grains/choco-shells-new.webp"],
    category: "Breakfast Cereals",
    brand: "Major Grains",
    weight: "350g",
    inStock: true,
    featured: true,
  },
  {
    slug: "major-moons-stars",
    name: "Major Grains Moons & Stars",
    shortDescription: "Fun shaped cereal with moons and stars.",
    description: "Major Grains Moons & Stars are playful shaped cereal pieces perfect for families.",
    price: "460",
    comparePrice: "580",
    imageUrl: "/assets/images/products/major-grains/moons-and-stars-new.webp",
    images: ["/assets/images/products/major-grains/moons-and-stars-new.webp"],
    category: "Breakfast Cereals",
    brand: "Major Grains",
    weight: "350g",
    inStock: true,
    featured: false,
  },

  // NIWALA PRODUCTS
  {
    slug: "niwala-budget-everyday",
    name: "Niwala Budget Everyday Rice 1kg",
    shortDescription: "Affordable daily use rice - great value.",
    description: "Niwala Budget Everyday is perfect for daily consumption with good quality.",
    price: "620",
    comparePrice: "750",
    imageUrl: "/assets/images/products/niwala/budget-everyday-1kg.jpg",
    images: ["/assets/images/products/niwala/budget-everyday-1kg.jpg"],
    category: "Rice & Grains",
    brand: "Niwala",
    weight: "1kg",
    inStock: true,
    featured: false,
  },
  {
    slug: "niwala-daily-sella",
    name: "Niwala Daily Sella Rice 1kg",
    shortDescription: "Premium sella rice for daily use.",
    description: "Niwala Daily Sella is quality rice with long grains.",
    price: "750",
    comparePrice: "900",
    imageUrl: "/assets/images/products/niwala/daily-sella-1kg.jpg",
    images: ["/assets/images/products/niwala/daily-sella-1kg.jpg"],
    category: "Rice & Grains",
    brand: "Niwala",
    weight: "1kg",
    inStock: true,
    featured: false,
  },
  {
    slug: "niwala-golden-daal-chana",
    name: "Golden Daal Chana Mix",
    shortDescription: "Lentil and chickpea mix - protein rich.",
    description: "Niwala Golden Daal Chana is a nutritious blend of lentils and chickpeas.",
    price: "520",
    comparePrice: "650",
    imageUrl: "/assets/images/products/niwala/golden-daal-chana.webp",
    images: ["/assets/images/products/niwala/golden-daal-chana.webp"],
    category: "Pulses & Legumes",
    brand: "Niwala",
    weight: "400g",
    inStock: true,
    featured: true,
  },
  {
    slug: "niwala-golden-daal-masoor",
    name: "Golden Daal Masoor",
    shortDescription: "Red lentils - quick cooking and nutritious.",
    description: "Niwala Golden Daal Masoor provides essential protein and fiber.",
    price: "480",
    comparePrice: "600",
    imageUrl: "/assets/images/products/niwala/golden-daal-masoor.webp",
    images: ["/assets/images/products/niwala/golden-daal-masoor.webp"],
    category: "Pulses & Legumes",
    brand: "Niwala",
    weight: "400g",
    inStock: true,
    featured: false,
  },
  {
    slug: "niwala-golden-daal-mong",
    name: "Golden Daal Mong",
    shortDescription: "Mung beans - mild flavor and easy to cook.",
    description: "Niwala Golden Daal Mong is a staple pulse for healthy meals.",
    price: "500",
    comparePrice: "620",
    imageUrl: "/assets/images/products/niwala/golden-daal-mong.webp",
    images: ["/assets/images/products/niwala/golden-daal-mong.webp"],
    category: "Pulses & Legumes",
    brand: "Niwala",
    weight: "400g",
    inStock: true,
    featured: false,
  },
  {
    slug: "niwala-golden-kabuli-channa",
    name: "Golden Kabuli Channa",
    shortDescription: "Chickpeas - versatile legume for curries and salads.",
    description: "Niwala Golden Kabuli Channa are premium chickpeas with great taste.",
    price: "540",
    comparePrice: "680",
    imageUrl: "/assets/images/products/niwala/golden-kabuli-channa.webp",
    images: ["/assets/images/products/niwala/golden-kabuli-channa.webp"],
    category: "Pulses & Legumes",
    brand: "Niwala",
    weight: "400g",
    inStock: true,
    featured: false,
  },
  {
    slug: "niwala-golden-sella",
    name: "Niwala Golden Sella Rice 1kg",
    shortDescription: "Premium golden sella rice.",
    description: "Niwala Golden Sella offers superior quality long grain rice.",
    price: "820",
    comparePrice: "1000",
    imageUrl: "/assets/images/products/niwala/golden-sella-1kg.jpg",
    images: ["/assets/images/products/niwala/golden-sella-1kg.jpg"],
    category: "Rice & Grains",
    brand: "Niwala",
    weight: "1kg",
    inStock: true,
    featured: true,
  },
  {
    slug: "niwala-royal-kainat",
    name: "Niwala Royal Kainat Rice 1kg",
    shortDescription: "Premium basmati rice - royal quality.",
    description: "Niwala Royal Kainat is our finest basmati rice selection.",
    price: "1200",
    comparePrice: "1500",
    imageUrl: "/assets/images/products/niwala/royal-kainat-1kg.jpg",
    images: ["/assets/images/products/niwala/royal-kainat-1kg.jpg"],
    category: "Rice & Grains",
    brand: "Niwala",
    weight: "1kg",
    inStock: true,
    featured: true,
    badge: "Premium",
  },

  // RIVERDALE PRODUCTS
  {
    slug: "riverdale-apple-jam",
    name: "Riverdale Apple Jam",
    shortDescription: "Fresh apple jam - naturally sweet.",
    description: "Riverdale Apple Jam is made from fresh apples with no artificial preservatives.",
    price: "380",
    comparePrice: "480",
    imageUrl: "/assets/images/products/riverdale/apple-jam.jpg",
    images: ["/assets/images/products/riverdale/apple-jam.jpg"],
    category: "Jams & Spreads",
    brand: "Riverdale",
    weight: "350g",
    inStock: true,
    featured: false,
  },
  {
    slug: "riverdale-mango-jam",
    name: "Riverdale Mango Jam",
    shortDescription: "Delicious mango jam - favorite breakfast spread.",
    description: "Riverdale Mango Jam brings the taste of fresh mangoes in every spoonful.",
    price: "420",
    comparePrice: "520",
    imageUrl: "/assets/images/products/riverdale/mango-jam.jpg",
    images: ["/assets/images/products/riverdale/mango-jam.jpg"],
    category: "Jams & Spreads",
    brand: "Riverdale",
    weight: "350g",
    inStock: true,
    featured: true,
    badge: "Best Seller",
  },
  {
    slug: "riverdale-peach-jam",
    name: "Riverdale Peach Jam",
    shortDescription: "Smooth peach jam with natural flavor.",
    description: "Riverdale Peach Jam offers a delightful fruity spread for your breakfast.",
    price: "410",
    comparePrice: "510",
    imageUrl: "/assets/images/products/riverdale/peach-jam.jpg",
    images: ["/assets/images/products/riverdale/peach-jam.jpg"],
    category: "Jams & Spreads",
    brand: "Riverdale",
    weight: "350g",
    inStock: true,
    featured: false,
  },
  {
    slug: "riverdale-tropical-tango",
    name: "Riverdale Tropical Tango",
    shortDescription: "Exotic tropical fruit jam blend.",
    description: "Riverdale Tropical Tango brings together flavors of tropical fruits.",
    price: "450",
    comparePrice: "560",
    imageUrl: "/assets/images/products/riverdale/tropical-tango.jpg",
    images: ["/assets/images/products/riverdale/tropical-tango.jpg"],
    category: "Jams & Spreads",
    brand: "Riverdale",
    weight: "350g",
    inStock: true,
    featured: true,
  },
];
